### ISSUE TITLE
Documentation reports a different key binding for 'Insert fenced code block'

### ISSUE THREAD

**Issue by schwarzie2478** [robole/vscode-markdown-shortcuts#2]
Hi, 

I tried out your extentions, thanks for making it.
I wanted to use it specifically for 'Insert fenced code block', but this is not correctly documented.
It is mapped to Ctrl+m,Ctrl+f in the json.
But your documentation says this is  'Insert Heading'?
I suspect this is a copy/paste error in the documentation,  
but because we can't see the name in the UI, this was annoying to figure out.

**Comment by robole** [comment]
Hi @schwarzie2478

Thanks for reporting the issue. 🙏 The README has been corrected, and a new version has been uploaded to the marketplace.

If you are happy with the extension(s), I would appreciate a positive review if you have the time. 🌟
