### ISSUE TITLE
Selecting text and converting it?

### ISSUE THREAD

**Issue by KeesCBakker** [robole/vscode-markdown-shortcuts#4]
Awesome extension. Love the way it inserts ordered and unordered lists.

I was wondering if we can add a new feature. I would love to be able to select text and turn it into a list. Like:

```
2 niet al te grote appels
40 gr rozijnen
2 eetlepels suiker
1 theelepel kaneel
```

Press some sort of a shortkey and it turns the lines into:

```
- 2 niet al te grote appels
- 40 gr rozijnen
- 2 eetlepels suiker
- 1 theelepel kaneel
```

Would that be possible?

**Comment by robole** [comment]
hi @KeesCBakker 

I am glad you like the extension.

This extension only provides keyboard shortcuts to existing markdown snippets. It is not the objective of the extension to add snippets or more functionality beyond that.

The `insert unordered list` snippet is a builtin snippet ([found here](https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/extensions/markdown-basics/snippets/markdown.code-snippets)) that has the functionality you are using . This snippet only inserts a new list.  This is the actual snippet:

```json
"Insert unordered list": {
		"prefix": "unordered list",
		"body": [
			"- ${1:first}",
			"- ${2:second}",
			"- ${3:third}",
			"$0"
		],
		"description": "Insert unordered list"
	},
```

It is not possible for a snippet to read the text from the clipboard _and_ tokenize the text to insert a dash before each line. You need to write some JS/TS code for this functionality.

I wrote another extension called [Marky Edit](https://marketplace.visualstudio.com/items?itemName=robole.marky-edit&ssr=false) that provides more advanced markdown editing functionality such as this. I suggest you try that instead. However, you will need to add your own keyboard shortcuts for any of the commands you want to use.

All the best

Rob
